/- SPDX-License-Identifier: Apache-2.0 -/

import SealV2
import Test.V2ValidationFixtures

/-!
# Field-warrant corpus + negative-witness mutation machinery

The SINGLE SOURCE OF TRUTH for the field-warrant fixtures and the
step-executing negative-control corpus. Both `Test/FieldWarrant.lean` (the
human SHOW suite) and `Test/FieldWarrantMutation.lean` (the mechanical
negative-witness harness) import this module, so there is one corpus, not two
that can drift.

## The negative witness (council requirement, 2026-07-23 01:56)

A hand tamper matrix proves a control CAN be broken. The stronger MECHANICAL
form is a *negative witness*: for a control that CLAIMS to measure reason R,
construct a mutant that removes R's discriminator and require the control's
outcome to CHANGE (the control "goes red for the asserted reason"). The
frisk-F1 defect class — a control whose Block is provided by its own gate, so
it stays green even when signature binding is removed — is caught mechanically
by exactly this: such a control is INSENSITIVE to the signature mutant and
SENSITIVE to its own gate mutant, the inverse of an honest signature control.

Two mutant families, both computed at RUNTIME (no per-mutant recompile):

* `M_sig` — `verifyNoSig`: verification with ONLY the Ed25519 conjunct
  dropped (registry lookup, hex decode, and wire-width checks kept). Models
  "the signature no longer binds the message bytes" and nothing else.
* `M_gate[G]` — `mutantStep` with gate `G` forced true. Models "gate G is
  disabled".

A control's **sensitivity profile** is (flips-under-M_sig, {gates whose
M_gate flips it}). The mechanical adequacy check `profileMatches`:

* `.signature` ⇒ flips under M_sig AND flips under NO gate mutant. (An honest
  signature control's forged envelope has an INVALID signature, so disabling
  any gate cannot rescue it; only restoring signature acceptance can.)
* `.gate G`   ⇒ does NOT flip under M_sig AND flips under exactly M_gate[G].
  (A gate red carries a VALID signature; only its own gate blocks, so only
  disabling that gate flips it — and the signature mutant is inert.)
* `.registry` ⇒ flips under neither (kept out of the signature/gate scoring;
  witnessed separately by `verifyEffect` fail-closed — `M_sig` deliberately
  keeps the registry lookup, so an unregistered id stays blocked).

A control whose profile does not match its declared reason is *passing for the
wrong reason* — the machine form of frisk F1.
-/

open SealV2 SealV2.Effect Test.V2ValidationFixtures

namespace Test.FieldWarrant

-- generated by test/v2/field_warrant_sign_fixture.py (encoder twin
-- self-checked against the EffectEnvelope.lean golden-vector pins)
def sigBase : String :=
  "d9872df81af96e56f2cc64dbc44ce2cf9f4e41c366eeb30dc4dd7c25b21abf9224a9f74f79c29a1522f1b9e08c4f63ff43f8b5bf8f493bcbc57454493b99d707"
/-- adapterType := "cli" — trips adapterGate. -/
def sigAdapterType : String :=
  "93680b1b544ab4e4338b274b068ec18e15ab681b8ef9d21ee3dc91274a6b983abf23273222c290f37944190ed300577b8dbdc2213443df40fa4648bf14d24b0a"
/-- adapterVersion := "9999-01-01" — trips adapterGate. -/
def sigAdapterVersion : String :=
  "4ffc9a82999b651dd567ca20adb73ff0bc856cdc48ea769ef884d4e06cd6b17b99994ab529e9a3c1d3ed518bc2f16e8b083b63071117f741e0b6fa0f85e1160d"
/-- session := "" — trips sessionGate (mandatory; the killed bypass). -/
def sigEmptySession : String :=
  "7d9cc17f9d3b23814202b72c4c52f11a9c39e06710804f706480a6a02d9718b770e5b5666a879f1e2074c9f9c73f5e01830d8ef393de086da9032abcda083e04"
/-- session := "session-2" — trips sessionGate. -/
def sigSession : String :=
  "de12dcf58cd31b44dd56548a650bcc65e31b73bff26faee4719e6762b074d585c2cdc902b4c67655d0680a62cbb06b37b8c1892316250a58e9e44e8d876c7a01"
/-- policyVersion := "" — trips policyVersionGate (mandatory; killed bypass). -/
def sigEmptyPolicyVersion : String :=
  "266a2d2fc0abfc4a28ea28da10dbf0d5a92d2f2c59cfc8f3def1d09c122eabbf5e8375aafe47e65a2d20a4a5b9a7945ff3826396e22b6c52390187c8f56ce10a"
/-- policyVersion := "policy-2" — trips policyVersionGate. -/
def sigPolicyVersion : String :=
  "f81f7e175df3206cde6c6473b21c16bad5ac7125812663e30840720fc2c5df6fe5dc17199cc2f09f97dc4415545c016de753b162a2d2bf55b9a8a4dc41af260d"
/-- expiresAt := 0 — trips expiryGate (mandatory; the killed 0=unset seat). -/
def sigZeroExpiry : String :=
  "4075dcbb5c2cba6df7903bf9bca673ad6f96f5a2e04c0f063b6c443f8cf7cdfebb3fadbe8eb46eee04753521f12d3cf125d1e4914d2be5e8fbfe413c3d09520a"
/-- expiresAt := 1 (< now) — trips expiryGate. -/
def sigExpired : String :=
  "856f143f6abcc2553e489b0dde398ce252328a6be510b3628cfa2a25baf6976ada8bae3ea3f437fa0cc9f3e5598878a9f9651eac7560caae39c01ab137c60f0a"
/-- issuedAt := 11 (> now) — trips issuedAtGate. -/
def sigFutureIssued : String :=
  "2ece399ead3189683705649d0efe6def900337d868d7bd8e25e442b79621b0b99ed4d6f15bc4414e42318a0cd9cc672a7eaba5b3cd57709cdc502bc1a1241901"
/-- effect := some ⟨"", "", ""⟩ — the retired all-empty sentinel is now a
    PRESENT claim; trips effectGate on mismatch with the derived effect. -/
def sigEmptyStringClaim : String :=
  "a716e625e64f42cccc7b099292be43ece1bff9e0dd3a8a1f3a6e095d0233f5b69a018c28df4247c50b9141105b77233c78ec9a174decf47e87308c24b968e001"
/-- effect.resource := "fs.read" — trips effectGate. -/
def sigEffectResource : String :=
  "793bb9e4428244d36899b6e7d4c30fef24462ecf73e5c3897d9557eb8079caa9f955d08f0bee76ca5d70de5c60e79b44f8de7d4ecda4d6a37ea001343c66dd04"
/-- effect.action := "delete" — trips effectGate. -/
def sigEffectAction : String :=
  "7bc66b7107ebdcdeee54ed6223b7a6b447a9c22294b5751e13f7ac32bc0f634abd7f94ca741131e83ce1155d8c78544ca06905e6e61d677433e5932be824ea02"
/-- effect.args amount 12.34→99 — trips effectGate. -/
def sigEffectArgs : String :=
  "b0d7da70deac9fc607d53b33ef3f0c24ce0c47172995105366809e8eaaa629f360f68aa53e91a3f89492cd39a5bc2990387b63e7283dd15b0d5b6ca5e9bda309"
/-- line swapped to an fs.read call — trips effectGate (kept F3 claim no
    longer derived from the judged line). -/
def sigLine : String :=
  "79c111ba87169cdd77fdb3ce4d846410392796918a9740b269e37d8510d3fb6d15b3e0a6c55e71bd2d355e41f2b9ab49ccaa4cb041836d5ef030d82151bcc60f"
/-- GREEN #2: effect := none — F3 DECLARED absent (signed presence byte). -/
def sigNoEffectClaim : String :=
  "4fd479259a1a2cb01af30c59f2bdba3d1d32350f37b89fe1d99330034a1fc2fc22b3a1ce91123ea8cce38477908eba17782f76afa76ff49741768419dc40c70d"

def authority : ByteArray :=
  ByteArray.mk (Array.range 32 |>.map fun i => UInt8.ofNat (0xa0 + i))

def envNonce : ByteArray :=
  ByteArray.mk (Array.range 32 |>.map UInt8.ofNat)

def registry : PrincipalRegistry :=
  [{ id := "alice", pubkey := testPublicKeyHex }]

/-- Twin registry for the keyId SIGNATURE RED: `alice2` is REGISTERED with
    the SAME pubkey, so the registry lookup succeeds and fail-closed cannot
    be the discriminator — only the signature over `frame(keyId)` can. -/
def registryTwin : PrincipalRegistry :=
  [{ id := "alice", pubkey := testPublicKeyHex },
   { id := "alice2", pubkey := testPublicKeyHex }]

def mediator : AdapterId := { type := "mcp", version := "2025-06-18" }

def baseArgs : String := "{\"database\":\"prod\",\"table\":\"users\",\"amount\":12.34}"

def baseClaim : EffectClaim :=
  { resource := "db.execute", action := "write", args := baseArgs }

/-- The warrant base: passes every gate against the fixture `baseState`
    (session-1, now=10, policy-1, ttl cap 300) with every mandatory binding
    populated and the F3 claim PRESENT. `line` is the fixture's `validRaw`,
    which `decide` Allows in `baseState`. -/
def baseEnvelope : EffectEnvelope :=
  { keyId := "alice"
    nonce := envNonce
    issuedAt := 5
    expiresAt := 100
    line := validRaw
    adapterType := "mcp"
    adapterVersion := "2025-06-18"
    session := "session-1"
    policyVersion := "policy-1"
    effect := some baseClaim }

/-- The old suite's line forgery / gate-red line: swaps to an fs.read call,
    so `deriveEffect` changes and `effectGate` trips. -/
def swappedLine : String :=
  "{\"method\":\"tools/call\",\"params\":{\"name\":\"fs.read\",\"action\":\"read\",\"arguments\":{}}}"

/-- The isolating line forgery: a WHITESPACE variant of `validRaw` (a space
    after `tools/call,`). Parses to the identical AST, so `deriveEffect` and
    the decision are unchanged and `effectGate` passes; only the signed BYTES
    differ. -/
def spacedRaw : String :=
  "{\"method\":\"tools/call\", \"params\":{\"name\":\"db.execute\",\"action\":\"write\",\"arguments\":{\"database\":\"prod\",\"table\":\"users\",\"amount\":12.34}}}"

def tamperedArgs : String :=
  "{\"database\":\"prod\",\"table\":\"users\",\"amount\":99}"

def emptyClaimEnv : EffectEnvelope :=
  { baseEnvelope with effect := some { resource := "", action := "", args := "" } }

def forgedNonce : ByteArray :=
  ByteArray.mk (Array.range 32 |>.map fun i => UInt8.ofNat (i + 1))

/-! ## Mutation machinery -/

/-- The six gates, as a selector. -/
inductive GateSel
  | adapter | session | effect | expiry | issuedAt | policyVersion
  deriving DecidableEq, Repr, BEq

def GateSel.name : GateSel → String
  | .adapter => "adapterGate"
  | .session => "sessionGate"
  | .effect => "effectGate"
  | .expiry => "expiryGate"
  | .issuedAt => "issuedAtGate"
  | .policyVersion => "policyVersionGate"

def allGates : List GateSel :=
  [.adapter, .session, .effect, .expiry, .issuedAt, .policyVersion]

/-- The reason a negative control asserts its Block. -/
inductive Reason
  | signature | gate (g : GateSel) | registry
  deriving DecidableEq, Repr, BEq

def Reason.describe : Reason → String
  | .signature => "signature"
  | .gate g => s!"gate:{g.name}"
  | .registry => "registry"

/-- One step-executing negative control, as DATA — the single source both the
    human suite and the mutation harness consume. `field` is the signed field
    whose warrant this control serves; `reason` is what its Block is claimed
    to measure. -/
structure Control where
  name : String
  field : String
  e : EffectEnvelope
  sig : String
  st : ApprovalState
  med : AdapterId
  reg : PrincipalRegistry
  reason : Reason
  /-- The envelope this control's `sig` was actually MINTED over — the diff
      base for the DERIVED perturbation set (frisk F-HARNESS-1 repair). For a
      `.signature` control this is the honestly-signed preimage the forgery
      departed from; `sigAdequate` mechanically re-verifies `sig` over it, so
      an invented preimage cannot pass. Gate/registry rows ignore it (their
      sig signs `e` itself; their perturbation is measured against
      `baseEnvelope`). -/
  mintedE : EffectEnvelope := baseEnvelope

/-- Real value of a named gate for a control's envelope + verifier config. -/
def gateValue : GateSel → AdapterId → ApprovalState → EffectEnvelope → Bool
  | .adapter, m, _, e => adapterGate m e
  | .session, _, s, e => sessionGate s e
  | .effect, m, _, e => effectGate m e
  | .expiry, _, s, e => expiryGate s e
  | .issuedAt, _, s, e => issuedAtGate s e
  | .policyVersion, _, s, e => policyVersionGate s e

/-- `verifyEffect` with ONLY the Ed25519 conjunct dropped — registry lookup,
    hex decode, authority/pubkey width, and wire-width checks all kept. Models
    "the signature no longer binds the message bytes" and nothing else. Returns
    a Bool (whether verification would succeed); never constructs the
    private-ctor `AuthenticatedId`. -/
def verifyNoSig (auth : ByteArray) (reg : PrincipalRegistry)
    (e : EffectEnvelope) (sig : String) : Bool :=
  match reg.find? (fun k => k.id == e.keyId) with
  | none => false
  | some k =>
      match hexDecode? k.pubkey, hexDecode? sig with
      | some pk, some _ => auth.size == 32 && pk.size == 32 && wireSizedB e
      | _, _ => false

/-- `effectStep` under a mutant: optionally drop the Ed25519 signature check
    (`neuterSig`) and/or force a set of gates true (`disabled`). With
    `neuterSig = false, disabled = []` this equals `effectStep`. -/
def mutantStep (neuterSig : Bool) (disabled : List GateSel)
    (auth : ByteArray) (reg : PrincipalRegistry) (med : AdapterId)
    (e : EffectEnvelope) (sig : String) (st : ApprovalState) : Decision :=
  let verified := if neuterSig then verifyNoSig auth reg e sig
                  else (verifyEffect auth reg e sig).isSome
  if verified then
    if allGates.all (fun g => disabled.contains g || gateValue g med st e) then
      SealV2.decide e.line st
    else .Block
  else .Block

def outAllow : Decision → Bool
  | .Allow _ => true
  | .Block => false

def Control.baseOutcome (c : Control) : Bool :=
  outAllow (mutantStep false [] authority c.reg c.med c.e c.sig c.st)

def Control.flipSig (c : Control) : Bool :=
  outAllow (mutantStep true [] authority c.reg c.med c.e c.sig c.st) != c.baseOutcome

def Control.flipGate (c : Control) (g : GateSel) : Bool :=
  outAllow (mutantStep false [g] authority c.reg c.med c.e c.sig c.st) != c.baseOutcome

def Control.sensGates (c : Control) : List GateSel :=
  allGates.filter c.flipGate

/-- The gates that are actually FALSE for this control's envelope + config. -/
def Control.gateFalseSet (c : Control) : List GateSel :=
  allGates.filter (fun g => gateValue g c.med c.st c.e == false)

/-- Disabling ALL of the control's failing gates flips it to Allow — i.e. the
    gates are the ONLY thing blocking (not a bad signature, not the registry).
    Robust to OVERDETERMINED gate reds (e.g. the stale row, which trips both
    `issuedAt` and `expiry` at once) where disabling a single gate is not
    enough to flip. -/
def Control.gatesAreSoleBlocker (c : Control) : Bool :=
  outAllow (mutantStep false c.gateFalseSet authority c.reg c.med c.e c.sig c.st)

/-- The mechanical adequacy check: does the control's sensitivity profile
    match its declared reason? A `false` here is a control passing for the
    wrong reason — the machine form of frisk F1.

    * `.signature` — flips under the signature mutant AND under NO gate mutant.
    * `.gate g` — inert under the signature mutant, `g` is genuinely a failing
      gate, and the failing gates are the sole blocker (so a gate red hiding a
      bad signature — which would NOT flip when its gates are disabled — is
      caught here, mirroring the suite's `sigVerifies=true` assertion). This
      form accepts overdetermined gate reds without demanding single-gate
      isolation the base envelope cannot provide.
    * `.registry` — inert under both mutants (`verifyNoSig` keeps the registry
      lookup, so an unregistered id stays blocked); witnessed separately by
      `verifyEffect` fail-closed. -/
def Control.profileMatches (c : Control) : Bool :=
  match c.reason with
  | .signature => c.flipSig && c.sensGates.isEmpty
  | .gate g => (!c.flipSig) && c.gateFalseSet.contains g && c.gatesAreSoleBlocker
  | .registry => (!c.flipSig) && c.sensGates.isEmpty && (!c.gatesAreSoleBlocker)

/-! ## Derived perturbation (frisk F-HARNESS-1 repair)

The claim-list join used to key on `Control.field` — an UNVERIFIED string —
so a genuine signature red could claim credit for a field it never touches
(the frisk's DISHONEST-A). The repair: DERIVE the perturbed field set by
diffing the presented envelope against the envelope the signature was minted
over, and key the join on that derived set. The label becomes a checked
display name, not a trust root. -/

/-- Field-labelled diff of the F3 claim seat (presence flip first). -/
def claimDiff : Option EffectClaim → Option EffectClaim → List String
  | none, none => []
  | some _, none => ["effectPresence"]
  | none, some _ => ["effectPresence"]
  | some a, some b =>
      (if a.resource != b.resource then ["effect.resource"] else []) ++
      (if a.action != b.action then ["effect.action"] else []) ++
      (if a.args != b.args then ["effect.args"] else [])

/-- Field-labelled diff of two envelopes: one label per signed seat that
    differs. Completeness against structure growth is NOT assumed here — the
    `patchField` roundtrip in `sigAdequate` closes that hole mechanically. -/
def envDiff (e base : EffectEnvelope) : List String :=
  (if e.keyId != base.keyId then ["keyId"] else []) ++
  (if e.nonce != base.nonce then ["nonce"] else []) ++
  (if e.issuedAt != base.issuedAt then ["issuedAt"] else []) ++
  (if e.expiresAt != base.expiresAt then ["expiresAt"] else []) ++
  (if e.line != base.line then ["line"] else []) ++
  (if e.adapterType != base.adapterType then ["adapterType"] else []) ++
  (if e.adapterVersion != base.adapterVersion then ["adapterVersion"] else []) ++
  (if e.session != base.session then ["session"] else []) ++
  (if e.policyVersion != base.policyVersion then ["policyVersion"] else []) ++
  claimDiff e.effect base.effect

/-- Copy ONE named signed field from `src` onto `dst`; `none` for an unknown
    label. Used by the roundtrip check: patching the single derived field onto
    the minted envelope must reproduce the forgery under the DERIVED `BEq`
    over the WHOLE structure — so a field `envDiff` cannot see (e.g. a seat
    added to `EffectEnvelope` later without updating `envDiff`) cannot hide a
    second perturbation. -/
def patchField (f : String) (src dst : EffectEnvelope) : Option EffectEnvelope :=
  match f with
  | "keyId" => some { dst with keyId := src.keyId }
  | "nonce" => some { dst with nonce := src.nonce }
  | "issuedAt" => some { dst with issuedAt := src.issuedAt }
  | "expiresAt" => some { dst with expiresAt := src.expiresAt }
  | "line" => some { dst with line := src.line }
  | "adapterType" => some { dst with adapterType := src.adapterType }
  | "adapterVersion" => some { dst with adapterVersion := src.adapterVersion }
  | "session" => some { dst with session := src.session }
  | "policyVersion" => some { dst with policyVersion := src.policyVersion }
  | "effectPresence" => some { dst with effect := src.effect }
  | "effect.resource" =>
      match src.effect, dst.effect with
      | some s, some d => some { dst with effect := some { d with resource := s.resource } }
      | _, _ => none
  | "effect.action" =>
      match src.effect, dst.effect with
      | some s, some d => some { dst with effect := some { d with action := s.action } }
      | _, _ => none
  | "effect.args" =>
      match src.effect, dst.effect with
      | some s, some d => some { dst with effect := some { d with args := s.args } }
      | _, _ => none
  | _ => none

/-- The reference envelope a control's perturbation is measured against:
    the signature's true preimage for `.signature` rows (mint-checked in
    `sigAdequate`), the warrant base for gate/registry rows (whose own sig
    signs `e` itself). -/
def Control.diffBase (c : Control) : EffectEnvelope :=
  match c.reason with
  | .signature => c.mintedE
  | _ => baseEnvelope

/-- The DERIVED perturbed-field set — what the control actually touches,
    computed from envelope bytes, not read off a label. -/
def Control.perturbedFields (c : Control) : List String :=
  envDiff c.e c.diffBase

/-- ADEQUACY for a `.signature` control — the label is derived-checked, never
    trusted (frisk F-HARNESS-1):

    1. **Mint validity** — `sig` genuinely verifies over `mintedE` under the
       control's own registry, so the diff base cannot be invented;
    2. **Singleton** — the forgery differs from the minted envelope in EXACTLY
       ONE derived field, and that field is the declared one;
    3. **Patch roundtrip** — copying that single field from the forgery onto
       the minted envelope reproduces the forgery under whole-structure `BEq`,
       so a seat `envDiff` misses cannot smuggle a second perturbation;
    4. **Bytes move** — the signed message bytes actually differ, tying the
       perturbation to the signature domain. -/
def Control.sigAdequate (c : Control) : Bool :=
  let mintValid := (verifyEffect authority c.reg c.mintedE c.sig).isSome
  let singleton :=
    match envDiff c.e c.mintedE with
    | [f] =>
        f == c.field &&
        (match patchField f c.e c.mintedE with
         | some patched => patched == c.e
         | none => false)
    | _ => false
  let bytesMove := effectMessage authority c.e != effectMessage authority c.mintedE
  mintValid && singleton && bytesMove

/-- Label adequacy for the WHOLE corpus. `.signature` rows get the full
    derived check; gate/registry rows must at least name a field they
    genuinely perturb relative to the warrant base (`effect.claim` is the
    umbrella label for the all-empty claim row, where every sub-field moves
    at once). -/
def Control.fieldAdequate (c : Control) : Bool :=
  match c.reason with
  | .signature => c.sigAdequate
  | _ =>
      let d := envDiff c.e baseEnvelope
      d.contains c.field ||
      (c.field == "effect.claim" && !d.isEmpty && d.all (·.startsWith "effect."))

/-- **The authoritative negative-control corpus** — every step-executing row of
    the SHOW suite, as data. 15 gate reds, 1 registry fail-closed, 11 signature
    reds. The two GREEN positives and the pure-encoding MESSAGE DISTINCTNESS
    rows are not here: greens are not negative controls, and the byte rows do
    not execute a step (they compare `effectMessage` bytes directly). -/
def corpus : List Control :=
  -- GATE REDS (valid signature, one gate tripped)
  [ { name := "adapterType=cli", field := "adapterType"
      e := { baseEnvelope with adapterType := "cli" }, sig := sigAdapterType
      st := baseState, med := mediator, reg := registry, reason := .gate .adapter }
  , { name := "adapterVersion=9999-01-01", field := "adapterVersion"
      e := { baseEnvelope with adapterVersion := "9999-01-01" }, sig := sigAdapterVersion
      st := baseState, med := mediator, reg := registry, reason := .gate .adapter }
  , { name := "session=\"\"", field := "session"
      e := { baseEnvelope with session := "" }, sig := sigEmptySession
      st := baseState, med := mediator, reg := registry, reason := .gate .session }
  , { name := "session=session-2", field := "session"
      e := { baseEnvelope with session := "session-2" }, sig := sigSession
      st := baseState, med := mediator, reg := registry, reason := .gate .session }
  , { name := "policyVersion=\"\"", field := "policyVersion"
      e := { baseEnvelope with policyVersion := "" }, sig := sigEmptyPolicyVersion
      st := baseState, med := mediator, reg := registry, reason := .gate .policyVersion }
  , { name := "policyVersion=policy-2", field := "policyVersion"
      e := { baseEnvelope with policyVersion := "policy-2" }, sig := sigPolicyVersion
      st := baseState, med := mediator, reg := registry, reason := .gate .policyVersion }
  , { name := "expiresAt=0", field := "expiresAt"
      e := { baseEnvelope with expiresAt := 0 }, sig := sigZeroExpiry
      st := baseState, med := mediator, reg := registry, reason := .gate .expiry }
  , { name := "expiresAt=1 (past)", field := "expiresAt"
      e := { baseEnvelope with expiresAt := 1 }, sig := sigExpired
      st := baseState, med := mediator, reg := registry, reason := .gate .expiry }
  , { name := "issuedAt=11 (future)", field := "issuedAt"
      e := { baseEnvelope with issuedAt := 11 }, sig := sigFutureIssued
      st := baseState, med := mediator, reg := registry, reason := .gate .issuedAt }
  , { name := "effect=some(\"\",\"\",\"\")", field := "effect.claim"
      e := emptyClaimEnv, sig := sigEmptyStringClaim
      st := baseState, med := mediator, reg := registry, reason := .gate .effect }
  , { name := "effect.resource=fs.read", field := "effect.resource"
      e := { baseEnvelope with effect := some { baseClaim with resource := "fs.read" } }
      sig := sigEffectResource
      st := baseState, med := mediator, reg := registry, reason := .gate .effect }
  , { name := "effect.action=delete", field := "effect.action"
      e := { baseEnvelope with effect := some { baseClaim with action := "delete" } }
      sig := sigEffectAction
      st := baseState, med := mediator, reg := registry, reason := .gate .effect }
  , { name := "effect.args amount=99", field := "effect.args"
      e := { baseEnvelope with effect := some { baseClaim with args := tamperedArgs } }
      sig := sigEffectArgs
      st := baseState, med := mediator, reg := registry, reason := .gate .effect }
  -- REGISTRY fail-closed (no gate; verifyEffect none on unregistered id)
  , { name := "keyId=mallory (unregistered)", field := "keyId"
      e := { baseEnvelope with keyId := "mallory" }, sig := sigBase
      st := baseState, med := mediator, reg := registry, reason := .registry }
  -- SIGNATURE REDS (all gates pass, only the signature blocks)
  , { name := "forged keyId=alice2 (twin-registered)", field := "keyId"
      e := { baseEnvelope with keyId := "alice2" }, sig := sigBase
      st := baseState, med := mediator, reg := registryTwin, reason := .signature }
  , { name := "forged nonce", field := "nonce"
      e := { baseEnvelope with nonce := forgedNonce }, sig := sigBase
      st := baseState, med := mediator, reg := registry, reason := .signature }
  , { name := "forged issuedAt=6 (in window)", field := "issuedAt"
      e := { baseEnvelope with issuedAt := 6 }, sig := sigBase
      st := baseState, med := mediator, reg := registry, reason := .signature }
  , { name := "forged expiresAt=101 (unexpired)", field := "expiresAt"
      e := { baseEnvelope with expiresAt := 101 }, sig := sigBase
      st := baseState, med := mediator, reg := registry, reason := .signature }
  , { name := "forged line (whitespace variant)", field := "line"
      e := { baseEnvelope with line := spacedRaw }, sig := sigBase
      st := baseState, med := mediator, reg := registry, reason := .signature }
  , { name := "forged adapterType=mcp2 (absent-form base)", field := "adapterType"
      e := { baseEnvelope with effect := none, adapterType := "mcp2" }, sig := sigNoEffectClaim
      st := baseState, med := { type := "mcp2", version := "2025-06-18" }
      reg := registry, reason := .signature
      mintedE := { baseEnvelope with effect := none } }
  , { name := "forged adapterVersion=2025-06-19", field := "adapterVersion"
      e := { baseEnvelope with adapterVersion := "2025-06-19" }, sig := sigBase
      st := baseState, med := { type := "mcp", version := "2025-06-19" }
      reg := registry, reason := .signature }
    -- NO session SIGNATURE RED: session is coupled into the decision layer's
    -- SIGNED approval (`approvalLiveFor` re-verifies the approval's Ed25519
    -- signature, which covers session). Aligning `sessionGate` desyncs that
    -- approval, so `decide` blocks independently of the envelope signature —
    -- the mutation harness proved no state alignment isolates session without
    -- minting a fresh approval fixture. Named gap; witnessed at the encoding
    -- level instead (`bytes[session]` + `effect_message_injective`).
  , { name := "forged policyVersion=policy-1x (state aligned)", field := "policyVersion"
      e := { baseEnvelope with policyVersion := "policy-1x" }, sig := sigBase
      st := { baseState with policyVersion := "policy-1x" }, med := mediator
      reg := registry, reason := .signature }
  , { name := "forged effect presence some→none", field := "effectPresence"
      e := { baseEnvelope with effect := none }, sig := sigBase
      st := baseState, med := mediator, reg := registry, reason := .signature }
  , { name := "forged effect presence none→some", field := "effectPresence"
      e := baseEnvelope, sig := sigNoEffectClaim
      st := baseState, med := mediator, reg := registry, reason := .signature
      mintedE := { baseEnvelope with effect := none } } ]

/-- The HAND-AUTHORED adequacy claim: every signed field that must carry a
    step-level signature witness. Lives with the corpus so both the mutation
    harness and the dishonest-control probe join against the SAME list; still
    hand-authored, independent of the corpus rows. The mutation harness's
    COVERAGE PARTITION cross-checks it against every label `envDiff` can emit,
    so dropping an entry fails LOUDLY instead of silently shrinking coverage
    (frisk F-HARNESS-2). -/
def requiredSignatureFields : List String :=
  ["keyId", "nonce", "issuedAt", "expiresAt", "line", "adapterType",
   "adapterVersion", "policyVersion", "effectPresence"]

/-- The naive one-signature forgery for a field, reusing `sigBase` against the
    base verifier config — the OLD (pre-F1) control shape. Used only by the
    frisk-reproduction section of the mutation harness. -/
def naiveForgery (field : String) (e : EffectEnvelope) (sig : String := sigBase) : Control :=
  { name := s!"naive forged {field}", field, e, sig
    st := baseState, med := mediator, reg := registry, reason := .signature }

/-- The pre-F1 forgery corpus the frisk analysed: forge one field, reuse the
    base signature, expect Block, CLAIM signature binding. Nine of these
    fourteen pass for the wrong reason; the mutation harness recounts it. -/
def naiveCorpus : List Control :=
  [ naiveForgery "keyId" { baseEnvelope with keyId := "alice2" }
  , naiveForgery "nonce" { baseEnvelope with nonce := forgedNonce }
  , naiveForgery "issuedAt" { baseEnvelope with issuedAt := 6 }
  , naiveForgery "expiresAt" { baseEnvelope with expiresAt := 101 }
  , naiveForgery "line" { baseEnvelope with line := swappedLine }
  , naiveForgery "adapterType" { baseEnvelope with adapterType := "mcp2" }
  , naiveForgery "adapterVersion" { baseEnvelope with adapterVersion := "2025-06-19" }
  , naiveForgery "session" { baseEnvelope with session := "session-1x" }
  , naiveForgery "policyVersion" { baseEnvelope with policyVersion := "policy-1x" }
  , naiveForgery "effect.resource"
      { baseEnvelope with effect := some { baseClaim with resource := "db.executex" } }
  , naiveForgery "effect.action"
      { baseEnvelope with effect := some { baseClaim with action := "writex" } }
  , naiveForgery "effect.args"
      { baseEnvelope with effect := some { baseClaim with args := "{}" } }
  , naiveForgery "effectPresence" { baseEnvelope with effect := none }
  , { naiveForgery "effectPresence" baseEnvelope sigNoEffectClaim with
      name := "naive forged effectPresence none→some" } ]

end Test.FieldWarrant
