/- SPDX-License-Identifier: Apache-2.0 -/

import SealV2
import Test.V2ValidationFixtures

/-!
# Field-warrant SHOW suite — negative controls for every signed envelope field

Ben's warrant doctrine (2026-07-22): every field inside the signature needs a
WHY (threat), a HOW (mechanism at file:line) and a SHOW — a runnable test
that goes RED when the field is tampered with, forged, replayed or dropped.
This file is the SHOW, ported from `feat/field-warrant` onto the Stage B2
reconciled `seal.effect/v2` shape. Real Ed25519 signatures (fixed documented
test seed, minted by `test/v2/field_warrant_sign_fixture.py`, whose
byte-encoder twin is self-checked against BOTH golden-vector pins in
`SealV2/EffectEnvelope.lean`).

**Polarity changes vs the field-warrant branch suite, recorded, not
smoothed over.** The campaign suite's second GREEN control ("seat form:
optional fields empty/0 → Allow") asserted the empty-value fail-open as
correct behaviour. Stage B2 kills that fail-open, so the control does not
survive with its polarity intact:

* session = ""            — was part of GREEN #2; now a GATE RED.
* policyVersion = ""      — was part of GREEN #2; now a GATE RED.
* expiresAt = 0           — was part of GREEN #2; now a GATE RED.
* effect claim ("","","") — was the GREEN #2 spelling of "no claim"; now a
  PRESENT claim, checked and RED on mismatch like any other.
* effect claim DECLARED ABSENT (`none`) — the one legitimately optional
  binding, and the only survivor of GREEN #2: optionality is a signed
  presence byte, so this green asserts declared absence, not a sentinel.

A test that had to be edited to accommodate a security fix is a finding:
the old control was the tripwire the doctrine is meant to catch.

Four control classes:

* GREEN — a fully gate-passing envelope is Allowed (twice: strong form with
  the F3 claim present, and declared-absent form with `effect := none`).
* GATE RED — an attacker WITH the registered key signs an envelope failing
  exactly one gate: valid signature, still `.Block`. Each control checks
  the specific gate Bool AND that the signature actually VERIFIES
  (`verifyEffect … |>.isSome`), so the Block is attributed to the gate,
  not to a malformed fixture signature. Exception, labelled: the
  `keyId=mallory` row has NO gate attribution — its Block is `verifyEffect`
  registry fail-closed (unregistered id), and the row asserts `isNone`.
* SIGNATURE RED — the isolating forgery controls (frisk F1 repair). Each
  row is two-stage: FIRST it proves no gate is the discriminator (all six
  gate Bools pass for the forged envelope under that row's verifier
  configuration), THEN it proves rejection comes from the signature alone
  (`verifyEffect` is `none`, step Blocks). Isolation is achieved by
  forging the field AND aligning the verifier-side trusted input so the
  matching gate passes: twin-registered `keyId` (same pubkey, different
  id), state with the forged `session`/`policyVersion`, mediator with the
  forged `adapterType`/`adapterVersion` (the type row rides the
  absent-form base because `effectGate` demands the MCP type for a present
  claim), a whitespace-variant `line` that parses to the SAME derived
  effect, and in-window `nonce`/`issuedAt`/`expiresAt` tampers (never
  gated / still inside their windows). Plus BOTH presence flips of the
  option block (some→none under the base signature, none→some under the
  absent-form signature) — the runnable `optEffect_inj`. If the signature
  stopped binding the forged field, the forgery would verify and the step
  would Allow: the row goes RED.
* MESSAGE DISTINCTNESS — the runnable per-field form of
  `effect_message_injective`: for every signed field (all ten, plus
  authority, plus each F3 subfield resource/action/args, plus the presence
  byte) a pair of inputs differing ONLY in that field must produce
  different `effectMessage` bytes. Goes RED the moment a field's bytes are
  dropped from the encoding.

NAMED GAP, stated honestly rather than faked: `effect.resource`,
`effect.action`, `effect.args` have NO runtime signature-isolated forgery
row. `effectGate` pins a present claim to `deriveEffect` of the UNCHANGED
signed line, so any single-subfield claim tamper is gate-red by
construction — there is no verifier configuration under which the gate
passes and only the signature discriminates. Their signature binding is
witnessed by the MESSAGE DISTINCTNESS rows, the two presence-flip
SIGNATURE REDs, and the kernel proofs (`optEffect_inj`,
`effect_message_injective`).

Also not showable here: envelope-nonce REPLAY (the enforcing store is host
state — BOUNDARY, exempted with reason in
`SealV2/EnvelopeCompleteness.lean`; there is no gate to trip), and field
DROP at runtime (the envelope is a fixed structure; drop coverage is the
ablation experiment plus the host twin's strict wire shape).
-/

open SealV2 SealV2.Effect Test.V2ValidationFixtures

namespace Test.FieldWarrant

-- generated by test/v2/field_warrant_sign_fixture.py (encoder twin
-- self-checked against the EffectEnvelope.lean golden-vector pins)
def sigBase : String :=
  "d9872df81af96e56f2cc64dbc44ce2cf9f4e41c366eeb30dc4dd7c25b21abf9224a9f74f79c29a1522f1b9e08c4f63ff43f8b5bf8f493bcbc57454493b99d707"
/-- adapterType := "cli" — trips adapterGate. -/
def sigAdapterType : String :=
  "93680b1b544ab4e4338b274b068ec18e15ab681b8ef9d21ee3dc91274a6b983abf23273222c290f37944190ed300577b8dbdc2213443df40fa4648bf14d24b0a"
/-- adapterVersion := "9999-01-01" — trips adapterGate. -/
def sigAdapterVersion : String :=
  "4ffc9a82999b651dd567ca20adb73ff0bc856cdc48ea769ef884d4e06cd6b17b99994ab529e9a3c1d3ed518bc2f16e8b083b63071117f741e0b6fa0f85e1160d"
/-- session := "" — trips sessionGate (mandatory; the killed bypass). -/
def sigEmptySession : String :=
  "7d9cc17f9d3b23814202b72c4c52f11a9c39e06710804f706480a6a02d9718b770e5b5666a879f1e2074c9f9c73f5e01830d8ef393de086da9032abcda083e04"
/-- session := "session-2" — trips sessionGate. -/
def sigSession : String :=
  "de12dcf58cd31b44dd56548a650bcc65e31b73bff26faee4719e6762b074d585c2cdc902b4c67655d0680a62cbb06b37b8c1892316250a58e9e44e8d876c7a01"
/-- policyVersion := "" — trips policyVersionGate (mandatory; killed bypass). -/
def sigEmptyPolicyVersion : String :=
  "266a2d2fc0abfc4a28ea28da10dbf0d5a92d2f2c59cfc8f3def1d09c122eabbf5e8375aafe47e65a2d20a4a5b9a7945ff3826396e22b6c52390187c8f56ce10a"
/-- policyVersion := "policy-2" — trips policyVersionGate. -/
def sigPolicyVersion : String :=
  "f81f7e175df3206cde6c6473b21c16bad5ac7125812663e30840720fc2c5df6fe5dc17199cc2f09f97dc4415545c016de753b162a2d2bf55b9a8a4dc41af260d"
/-- expiresAt := 0 — trips expiryGate (mandatory; the killed 0=unset seat). -/
def sigZeroExpiry : String :=
  "4075dcbb5c2cba6df7903bf9bca673ad6f96f5a2e04c0f063b6c443f8cf7cdfebb3fadbe8eb46eee04753521f12d3cf125d1e4914d2be5e8fbfe413c3d09520a"
/-- expiresAt := 1 (< now) — trips expiryGate. -/
def sigExpired : String :=
  "856f143f6abcc2553e489b0dde398ce252328a6be510b3628cfa2a25baf6976ada8bae3ea3f437fa0cc9f3e5598878a9f9651eac7560caae39c01ab137c60f0a"
/-- issuedAt := 11 (> now) — trips issuedAtGate. -/
def sigFutureIssued : String :=
  "2ece399ead3189683705649d0efe6def900337d868d7bd8e25e442b79621b0b99ed4d6f15bc4414e42318a0cd9cc672a7eaba5b3cd57709cdc502bc1a1241901"
/-- effect := some ⟨"", "", ""⟩ — the retired all-empty sentinel is now a
    PRESENT claim; trips effectGate on mismatch with the derived effect. -/
def sigEmptyStringClaim : String :=
  "a716e625e64f42cccc7b099292be43ece1bff9e0dd3a8a1f3a6e095d0233f5b69a018c28df4247c50b9141105b77233c78ec9a174decf47e87308c24b968e001"
/-- effect.resource := "fs.read" — trips effectGate. -/
def sigEffectResource : String :=
  "793bb9e4428244d36899b6e7d4c30fef24462ecf73e5c3897d9557eb8079caa9f955d08f0bee76ca5d70de5c60e79b44f8de7d4ecda4d6a37ea001343c66dd04"
/-- effect.action := "delete" — trips effectGate. -/
def sigEffectAction : String :=
  "7bc66b7107ebdcdeee54ed6223b7a6b447a9c22294b5751e13f7ac32bc0f634abd7f94ca741131e83ce1155d8c78544ca06905e6e61d677433e5932be824ea02"
/-- effect.args amount 12.34→99 — trips effectGate. -/
def sigEffectArgs : String :=
  "b0d7da70deac9fc607d53b33ef3f0c24ce0c47172995105366809e8eaaa629f360f68aa53e91a3f89492cd39a5bc2990387b63e7283dd15b0d5b6ca5e9bda309"
/-- line swapped to an fs.read call — trips effectGate (kept F3 claim no
    longer derived from the judged line). -/
def sigLine : String :=
  "79c111ba87169cdd77fdb3ce4d846410392796918a9740b269e37d8510d3fb6d15b3e0a6c55e71bd2d355e41f2b9ab49ccaa4cb041836d5ef030d82151bcc60f"
/-- GREEN #2: effect := none — F3 DECLARED absent (signed presence byte). -/
def sigNoEffectClaim : String :=
  "4fd479259a1a2cb01af30c59f2bdba3d1d32350f37b89fe1d99330034a1fc2fc22b3a1ce91123ea8cce38477908eba17782f76afa76ff49741768419dc40c70d"

def authority : ByteArray :=
  ByteArray.mk (Array.range 32 |>.map fun i => UInt8.ofNat (0xa0 + i))

def envNonce : ByteArray :=
  ByteArray.mk (Array.range 32 |>.map UInt8.ofNat)

def registry : PrincipalRegistry :=
  [{ id := "alice", pubkey := testPublicKeyHex }]

/-- Twin registry for the keyId SIGNATURE RED: `alice2` is REGISTERED with
    the SAME pubkey, so the registry lookup succeeds and fail-closed cannot
    be the discriminator — only the signature over `frame(keyId)` can. -/
def registryTwin : PrincipalRegistry :=
  [{ id := "alice", pubkey := testPublicKeyHex },
   { id := "alice2", pubkey := testPublicKeyHex }]

def mediator : AdapterId := { type := "mcp", version := "2025-06-18" }

def baseArgs : String := "{\"database\":\"prod\",\"table\":\"users\",\"amount\":12.34}"

def baseClaim : EffectClaim :=
  { resource := "db.execute", action := "write", args := baseArgs }

/-- The warrant base: passes every gate against the fixture `baseState`
    (session-1, now=10, policy-1, ttl cap 300) with every mandatory binding
    populated and the F3 claim PRESENT. `line` is the fixture's `validRaw`,
    which `decide` Allows in `baseState`. -/
def baseEnvelope : EffectEnvelope :=
  { keyId := "alice"
    nonce := envNonce
    issuedAt := 5
    expiresAt := 100
    line := validRaw
    adapterType := "mcp"
    adapterVersion := "2025-06-18"
    session := "session-1"
    policyVersion := "policy-1"
    effect := some baseClaim }

/-- One control: run `effectStep`, compare Allow/Block against expectation,
    (when given) check the attributing gate Bool, and (when given) check
    whether the fixture signature VERIFIES — `some true` for gate reds
    (the Block must not be hiding a malformed signature), `some false` for
    the registry fail-closed row. -/
def control (name : String) (e : EffectEnvelope) (sig : String)
    (state : ApprovalState) (expectAllow : Bool)
    (gate : Option (String × Bool) := none)
    (sigValid : Option Bool := none) : IO Bool := do
  let d := effectStep authority registry mediator e sig state
  let allowed := match d with | .Allow _ => true | .Block => false
  let stepOk := allowed == expectAllow
  let gateOk := match gate with
    | none => true
    | some (_, got) => got == false
  let verified := (verifyEffect authority registry e sig).isSome
  let sigOk := match sigValid with
    | none => true
    | some want => verified == want
  let verdict := if stepOk && gateOk && sigOk then "PASS" else "FAIL"
  let gateNote := match gate with
    | none => ""
    | some (gname, got) => s!" [{gname}={got}]"
  let sigNote := match sigValid with
    | none => ""
    | some want => s!" [sigVerifies={verified} expected={want}]"
  IO.println s!"{verdict}  {name}: step={if allowed then "Allow" else "Block"} expected={if expectAllow then "Allow" else "Block"}{gateNote}{sigNote}"
  pure (stepOk && gateOk && sigOk)

/-- SIGNATURE RED runner — the isolating forgery control, two-stage:

    1. every one of the six gates must PASS for the forged envelope under
       this row's verifier configuration (state/mediator/registry aligned
       with the forgery) — proving no gate is the discriminator;
    2. `verifyEffect` must be `none` and the step must Block — proving the
       signature is the ONLY thing standing.

    If signature binding for the forged field were removed (its bytes
    dropped from `effectMessage` on both signer and verifier side), stage 2
    inverts: the reused signature verifies, the gates still pass, and the
    step Allows — this control goes RED. -/
def sigRed (name : String) (e : EffectEnvelope) (sig : String)
    (st : ApprovalState) (med : AdapterId)
    (reg : PrincipalRegistry := registry) : IO Bool := do
  let gates : List (String × Bool) :=
    [("adapterGate", adapterGate med e),
     ("sessionGate", sessionGate st e),
     ("effectGate", effectGate med e),
     ("expiryGate", expiryGate st e),
     ("issuedAtGate", issuedAtGate st e),
     ("policyVersionGate", policyVersionGate st e)]
  let failedGates := gates.filter (fun g => !g.2) |>.map (·.1)
  let gatesPass := failedGates.isEmpty
  let verified := (verifyEffect authority reg e sig).isSome
  let blocked := match effectStep authority reg med e sig st with
    | .Allow _ => false | .Block => true
  let ok := gatesPass && !verified && blocked
  let verdict := if ok then "PASS" else "FAIL"
  let gateNote := if gatesPass then "all 6 gates pass"
    else s!"gates FAILED: {failedGates}"
  IO.println s!"{verdict}  {name}: [{gateNote}] [sigVerifies={verified} expected=false] [step={if blocked then "Block" else "Allow"} expected=Block]"
  pure ok

/-- MESSAGE DISTINCTNESS runner — runnable per-field
    `effect_message_injective`: the two messages (inputs differing ONLY in
    the named field) must be different bytes. Goes RED the moment the
    field's bytes are dropped from the encoding. -/
def byteRow (name : String) (m₁ m₂ : ByteArray) : IO Bool := do
  let ok := m₁ != m₂
  IO.println s!"{if ok then "PASS" else "FAIL"}  bytes[{name}]: messages distinct={ok}"
  pure ok

def main : IO UInt32 := do
  let s := baseState
  let stale : ApprovalState := { baseState with now := 400 }
  let mut results : List Bool := []

  IO.println "== GREEN controls =="
  results := results ++ [← control "green: strong form (all bindings populated, F3 claim present)"
    baseEnvelope sigBase s true]
  results := results ++ [← control "green: F3 claim declared absent (effect := none, signed presence byte)"
    { baseEnvelope with effect := none } sigNoEffectClaim s true]

  IO.println "== GATE REDS (VERIFIED signature, one gate tripped) =="
  results := results ++ [← control "adapterType=cli"
    { baseEnvelope with adapterType := "cli" } sigAdapterType s false
    (some ("adapterGate", adapterGate mediator { baseEnvelope with adapterType := "cli" }))
    (sigValid := some true)]
  results := results ++ [← control "adapterVersion=9999-01-01"
    { baseEnvelope with adapterVersion := "9999-01-01" } sigAdapterVersion s false
    (some ("adapterGate", adapterGate mediator { baseEnvelope with adapterVersion := "9999-01-01" }))
    (sigValid := some true)]
  results := results ++ [← control "session=\"\" (killed bypass: was GREEN seat form on feat/field-warrant)"
    { baseEnvelope with session := "" } sigEmptySession s false
    (some ("sessionGate", sessionGate s { baseEnvelope with session := "" }))
    (sigValid := some true)]
  results := results ++ [← control "session=session-2"
    { baseEnvelope with session := "session-2" } sigSession s false
    (some ("sessionGate", sessionGate s { baseEnvelope with session := "session-2" }))
    (sigValid := some true)]
  results := results ++ [← control "policyVersion=\"\" (killed bypass: was GREEN seat form)"
    { baseEnvelope with policyVersion := "" } sigEmptyPolicyVersion s false
    (some ("policyVersionGate", policyVersionGate s { baseEnvelope with policyVersion := "" }))
    (sigValid := some true)]
  results := results ++ [← control "policyVersion=policy-2"
    { baseEnvelope with policyVersion := "policy-2" } sigPolicyVersion s false
    (some ("policyVersionGate", policyVersionGate s { baseEnvelope with policyVersion := "policy-2" }))
    (sigValid := some true)]
  results := results ++ [← control "expiresAt=0 (killed bypass: was GREEN seat form)"
    { baseEnvelope with expiresAt := 0 } sigZeroExpiry s false
    (some ("expiryGate", expiryGate s { baseEnvelope with expiresAt := 0 }))
    (sigValid := some true)]
  results := results ++ [← control "expiresAt=1 in the past"
    { baseEnvelope with expiresAt := 1 } sigExpired s false
    (some ("expiryGate", expiryGate s { baseEnvelope with expiresAt := 1 }))
    (sigValid := some true)]
  results := results ++ [← control "issuedAt=11 future-dated"
    { baseEnvelope with issuedAt := 11 } sigFutureIssued s false
    (some ("issuedAtGate", issuedAtGate s { baseEnvelope with issuedAt := 11 }))
    (sigValid := some true)]
  results := results ++ [← control "base envelope judged at now=400 (stale, window 300)"
    baseEnvelope sigBase stale false
    (some ("issuedAtGate", issuedAtGate stale baseEnvelope))
    (sigValid := some true)]
  let emptyClaim : EffectEnvelope :=
    { baseEnvelope with effect := some { resource := "", action := "", args := "" } }
  results := results ++ [← control "effect=some(\"\",\"\",\"\") (retired sentinel is now a checked claim)"
    emptyClaim sigEmptyStringClaim s false
    (some ("effectGate", effectGate mediator emptyClaim))
    (sigValid := some true)]
  results := results ++ [← control "effect.resource=fs.read"
    { baseEnvelope with effect := some { baseClaim with resource := "fs.read" } } sigEffectResource s false
    (some ("effectGate", effectGate mediator
      { baseEnvelope with effect := some { baseClaim with resource := "fs.read" } }))
    (sigValid := some true)]
  results := results ++ [← control "effect.action=delete"
    { baseEnvelope with effect := some { baseClaim with action := "delete" } } sigEffectAction s false
    (some ("effectGate", effectGate mediator
      { baseEnvelope with effect := some { baseClaim with action := "delete" } }))
    (sigValid := some true)]
  let tamperedArgs := "{\"database\":\"prod\",\"table\":\"users\",\"amount\":99}"
  results := results ++ [← control "effect.args amount=99"
    { baseEnvelope with effect := some { baseClaim with args := tamperedArgs } } sigEffectArgs s false
    (some ("effectGate", effectGate mediator
      { baseEnvelope with effect := some { baseClaim with args := tamperedArgs } }))
    (sigValid := some true)]
  let swappedLine := "{\"method\":\"tools/call\",\"params\":{\"name\":\"fs.read\",\"action\":\"read\",\"arguments\":{}}}"
  results := results ++ [← control "line swapped under kept F3 claim"
    { baseEnvelope with line := swappedLine } sigLine s false
    (some ("effectGate", effectGate mediator { baseEnvelope with line := swappedLine }))
    (sigValid := some true)]
  results := results ++ [← control "keyId=mallory (NO gate: verifyEffect registry fail-closed)"
    { baseEnvelope with keyId := "mallory" } sigBase s false
    (sigValid := some false)]

  IO.println "== SIGNATURE REDS (all gates pass, ONLY the signature blocks) =="
  -- keyId: alice2 is REGISTERED with the same pubkey (twin registry), so
  -- neither fail-closed nor any gate discriminates — only frame(keyId).
  results := results ++ [← sigRed "forged keyId=alice2 (twin-registered, same pubkey)"
    { baseEnvelope with keyId := "alice2" } sigBase s mediator (reg := registryTwin)]
  -- nonce: never gated (replay ledger is BOUNDARY) — signature only.
  results := results ++ [← sigRed "forged nonce (+1 bytes)"
    { baseEnvelope with nonce := ByteArray.mk (Array.range 32 |>.map fun i => UInt8.ofNat (i + 1)) }
    sigBase s mediator]
  -- issuedAt/expiresAt: forged values stay INSIDE the gate windows.
  results := results ++ [← sigRed "forged issuedAt=6 (still in freshness window)"
    { baseEnvelope with issuedAt := 6 } sigBase s mediator]
  results := results ++ [← sigRed "forged expiresAt=101 (still unexpired, nonzero)"
    { baseEnvelope with expiresAt := 101 } sigBase s mediator]
  -- line: whitespace variant — parses to the SAME AST, so deriveEffect and
  -- the decision are unchanged and effectGate passes; only the BYTES differ.
  let spacedRaw := "{\"method\":\"tools/call\", \"params\":{\"name\":\"db.execute\",\"action\":\"write\",\"arguments\":{\"database\":\"prod\",\"table\":\"users\",\"amount\":12.34}}}"
  results := results ++ [← sigRed "forged line (whitespace variant, same derived effect)"
    { baseEnvelope with line := spacedRaw } sigBase s mediator]
  -- adapterType: mediator aligned with the forgery so adapterGate passes;
  -- rides the ABSENT-form base because effectGate demands the MCP type for
  -- a present claim.
  results := results ++ [← sigRed "forged adapterType=mcp2 (mediator aligned, absent-form base)"
    { baseEnvelope with effect := none, adapterType := "mcp2" } sigNoEffectClaim s
    { type := "mcp2", version := "2025-06-18" }]
  results := results ++ [← sigRed "forged adapterVersion=2025-06-19 (mediator aligned)"
    { baseEnvelope with adapterVersion := "2025-06-19" } sigBase s
    { type := "mcp", version := "2025-06-19" }]
  -- session/policyVersion: verifier state aligned with the forgery so the
  -- equality gates pass.
  results := results ++ [← sigRed "forged session=session-1x (state aligned)"
    { baseEnvelope with session := "session-1x" } sigBase
    { baseState with session := "session-1x" } mediator]
  results := results ++ [← sigRed "forged policyVersion=policy-1x (state aligned)"
    { baseEnvelope with policyVersion := "policy-1x" } sigBase
    { baseState with policyVersion := "policy-1x" } mediator]
  -- both presence flips: runnable optEffect_inj (gates pass on both sides
  -- of the flip; the signed presence byte is the only discriminator).
  results := results ++ [← sigRed "forged effect presence flip some→none"
    { baseEnvelope with effect := none } sigBase s mediator]
  results := results ++ [← sigRed "forged effect presence flip none→some"
    baseEnvelope sigNoEffectClaim s mediator]

  IO.println "== MESSAGE DISTINCTNESS (runnable effect_message_injective, per field) =="
  let msgOf (e : EffectEnvelope) : ByteArray := effectMessage authority e
  let mBase := msgOf baseEnvelope
  let authority2 := ByteArray.mk (Array.range 32 |>.map fun i => UInt8.ofNat (0xb0 + i))
  results := results ++ [← byteRow "authority" mBase (effectMessage authority2 baseEnvelope)]
  results := results ++ [← byteRow "keyId" mBase (msgOf { baseEnvelope with keyId := "alice2" })]
  results := results ++ [← byteRow "nonce" mBase
    (msgOf { baseEnvelope with nonce := ByteArray.mk (Array.range 32 |>.map fun i => UInt8.ofNat (i + 1)) })]
  results := results ++ [← byteRow "issuedAt" mBase (msgOf { baseEnvelope with issuedAt := 6 })]
  results := results ++ [← byteRow "expiresAt" mBase (msgOf { baseEnvelope with expiresAt := 101 })]
  results := results ++ [← byteRow "line" mBase (msgOf { baseEnvelope with line := spacedRaw })]
  results := results ++ [← byteRow "adapterType" mBase (msgOf { baseEnvelope with adapterType := "mcp2" })]
  results := results ++ [← byteRow "adapterVersion" mBase (msgOf { baseEnvelope with adapterVersion := "2025-06-19" })]
  results := results ++ [← byteRow "session" mBase (msgOf { baseEnvelope with session := "session-1x" })]
  results := results ++ [← byteRow "policyVersion" mBase (msgOf { baseEnvelope with policyVersion := "policy-1x" })]
  results := results ++ [← byteRow "effect.resource" mBase
    (msgOf { baseEnvelope with effect := some { baseClaim with resource := "db.executex" } })]
  results := results ++ [← byteRow "effect.action" mBase
    (msgOf { baseEnvelope with effect := some { baseClaim with action := "writex" } })]
  results := results ++ [← byteRow "effect.args" mBase
    (msgOf { baseEnvelope with effect := some { baseClaim with args := "{}" } })]
  results := results ++ [← byteRow "effect presence" mBase (msgOf { baseEnvelope with effect := none })]

  let failures := results.filter (fun r => !r) |>.length
  IO.println s!"field-warrant: {results.length} controls, {failures} failures"
  pure (if failures == 0 then 0 else 1)

end Test.FieldWarrant

def main : IO UInt32 := Test.FieldWarrant.main
